### ISSUE TITLE
question on train_logmap_network

### ISSUE THREAD

**Issue by TLi347** [mrakotosaon/dse-meshing#1]
When run train_logmap_network.py, it shows
         "gather() got an unexpected keyword argument 'batch_dims'"

tf1.5 can't support tf.random.normal and tf.math

**Comment by mrakotosaon** [comment]
Hi @TLi347 

Thank you for your question. There was indeed an error in my README. I am using tensorflow 1.15 and not 1.5. Please note that the I also tested the code with tf 1.14.

Thank you again and sorry for this issue.
