### ISSUE TITLE
Questions for run.sh and eval_align_meshes

### ISSUE THREAD

**Issue by TLi347** [mrakotosaon/dse-meshing#2]
Hi,

When I run run.sh and eval_align_mesh.py, I got error:

> FileNotFoundError: No such file or directory: '~/dse-meshing/data/test_data/aligned_prediction/proj_maps_squirrel.npy'

Can you help with this?

Many thanks

**Comment by mrakotosaon** [comment]
Hi @TLi347 

Thank you for making me aware of this issue. It is now corrected on github. There was a commented line that you should uncomment and replace by the next line in the file logmap_alignment/align_patches.py  l.111.

Sorry for the inconvenience and thank you again.

**Comment by TLi347** [comment]
> Hi @TLi347
> 
> Thank you for making me aware of this issue. It is now corrected on github. There was a commented line that you should uncomment and replace by the next line in the file logmap_alignment/align_patches.py l.111.
> 
> Sorry for the inconvenience and thank you again.

**Comment by TLi347** [comment]
> Hi @TLi347
> 
> Thank you for making me aware of this issue. It is now corrected on github. There was a commented line that you should uncomment and replace by the next line in the file logmap_alignment/align_patches.py l.111.
> 
> Sorry for the inconvenience and thank you again.

Hi @mrakotosaon ,

It's ok. Thank you for such a detailed reply.

**Comment by TLi347** [comment]
> Hi @TLi347
> 
> Thank you for making me aware of this issue. It is now corrected on github. There was a commented line that you should uncomment and replace by the next line in the file logmap_alignment/align_patches.py l.111.
> 
> Sorry for the inconvenience and thank you again.

Hi @mrakotosaon ,

It's ok. Thank you for such a detailed reply.
