### ISSUE TITLE
Mesh visualization

### ISSUE THREAD

**Issue by unknownue** [mrakotosaon/dse-meshing#4]
Hey, the visual effect of triangles used in paper is great. I want to use it in my projects.
Can you release the corresponding visualization code or links to its implementation?

**Comment by mrakotosaon** [comment]
Hi @unknownue ,
We used code from this great blender toolbox [https://github.com/HTDerekLiu/BlenderToolbox](https://github.com/HTDerekLiu/BlenderToolbox) for the visualization.

**Comment by unknownue** [comment]
Thanks, I try to implement this based on [this](https://github.com/yuki-koyama/blender-cli-rendering#11_mesh_visualizationpy), but still encounter some problems.
BlenderToolbox provides more specific implementation for visualizing mesh. It is really helpful.
