### ISSUE TITLE
Problem with run.sh 

### ISSUE THREAD

**Issue by WildEchoes** [mrakotosaon/dse-meshing#9]
I use my point cloud to reconstruct, but some problems appear.  They appear together.

# error1
Traceback (most recent call last):
  File "logmap_alignment/align_patches.py", line 155, in <module>
    main(file)
  File "logmap_alignment/align_patches.py", line 121, in main
    np.copyto(shared_predicted_map, predicted_map)
ValueError: could not broadcast input array from shape (49860,31,3) into shape (10000,31,3)

# error2
Traceback (most recent call last):
  File "logmap_alignment/eval_align_meshes.py", line 115, in <module>
    reconstruct(name)
  File "logmap_alignment/eval_align_meshes.py", line 69, in reconstruct
    corrected_predicted_map = np.load(os.path.join(res_path, "corrected_maps_{}.npy".format(name)))
  File "/home/yy/anaconda3/envs/dse-meshing2/lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/yy/reconstruction/dse-meshing/data/test_data/aligned_prediction/corrected_maps_tetrahedron_40K-1%N-ours-up.npy'

# error3
Traceback (most recent call last):
  File "triangle_selection/select1.py", line 42, in <module>
    bbox_diag.append(write_candidates(file))
  File "triangle_selection/select1.py", line 14, in write_candidates
    trig_probs = np.load(os.path.join(align_path, "patch_frequency_count_{}.npy".format(file)))
  File "/home/yy/anaconda3/envs/dse-meshing2/lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/yy/reconstruction/dse-meshing/data/test_data/aligned_prediction/patch_frequency_count_tetrahedron_40K-1%N-ours-up.npy'

**Comment by WildEchoes** [comment]
I find a way to solve this problem. Maybe you should make the number of the point cloud is a multiple of 10000.

**Comment by WildEchoes** [comment]
> I find a way to solve this problem. Maybe you should make the number of the point cloud is a multiple of 10000.

Sometimes it doesn't work. Could you tell me if there are some limitations in number of point cloud?

**Comment by mrakotosaon** [comment]
Hi @YuanYe-99 ,
I think I unfortunately wrote the code with the size of the point cloud hard coded. If you replace 10000 with a variable of the size of your point cloud (n_points ?) it should work. Thank you for pointing this out. Then error 2 and 3 should be because the files created by align_patches.py are not there because it failed.
I hope this helps.
Best

**Comment by WildEchoes** [comment]
> Hi @YuanYe-99 , I think I unfortunately wrote the code with the size of the point cloud hard coded. If you replace 10000 with a variable of the size of your point cloud (n_points ?) it should work. Thank you for pointing this out. Then error 2 and 3 should be because the files created by align_patches.py are not there because it failed. I hope this helps. Best

Thanks for your help! After changing this part of the code I have solved this problem.
